### ISSUE TITLE
libzopfli.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WtfJoke** [le0pard/zopfli-ffi#1]
Hi there

I wanted to test your wrapper. Installation worked (I used the zopfli fork you provided).
However when I require 'zopfli_ffi' I get an exception:

```
LoadError: Could not open library '/home/mw/.rvm/gems/ruby-2.4.2/gems/zopfli-ffi-0.1.1/ext/zopfli_ffi/x86_64-linux/libzopfli_ffi.so': libzopfli.so.1: cannot open shared object file: No such file or directory
	from /home/mw/.rvm/gems/ruby-2.4.2/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
	from /home/mw/.rvm/gems/ruby-2.4.2/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
	from /home/mw/.rvm/gems/ruby-2.4.2/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
	from /home/mw/.rvm/gems/ruby-2.4.2/gems/zopfli-ffi-0.1.1/lib/zopfli_ffi.rb:7:in `<module:C>'
	from /home/mw/.rvm/gems/ruby-2.4.2/gems/zopfli-ffi-0.1.1/lib/zopfli_ffi.rb:5:in `<module:Zopfli>'
	from /home/mw/.rvm/gems/ruby-2.4.2/gems/zopfli-ffi-0.1.1/lib/zopfli_ffi.rb:4:in `<top (required)>'
	from /home/mw/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/mw/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/mw/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /home/mw/.rvm/rubies/ruby-2.4.2/bin/irb:11:in `<main>'
```

an `ls` on that directory shows:
```
~/.rvm/gems/ruby-2.4.2/gems/zopfli-ffi-0.1.1/ext/zopfli_ffi/x86_64-linux
$ ls
libzopfli_ffi.so  zopfli_ffi.o
```

Do you have any ideas why thats the case?

Thanks

**Comment by le0pard** [comment]
Did you trying `zlib1g-dev` from linux packages? I am right now not near laptop - cannot check your problem.

**Comment by WtfJoke** [comment]
Yeah I installed all dependencies (including zlib1g-dev) provided by the readme.

**Comment by le0pard** [comment]
@WtfJoke why in this case you are using zopfli fork? It is just form Mac OS system.

**Comment by le0pard** [comment]
@WtfJoke in this case try to use zopfli from packages system (deb, yum), not a fork

**Comment by WtfJoke** [comment]
That somehow didnt work as well... I cant remember the reason, sorry 😕 . But i'll close this, as I switched to another solution without zopfli. 

Thanks you for your support.
